FROM node:23-alpine
RUN npm install -g pnpm

WORKDIR /turbo_app
COPY ./package.json ./package.json
COPY ./pnpm-lock.yaml ./pnpm-lock.yaml
COPY ./packages/db/package.json ./packages/db/package.json

COPY ./packages/db ./packages/db

COPY ./apps/web/package.json ./apps/web/package.json

RUN pnpm install

COPY . .

RUN pnpm db:generate

WORKDIR /turbo_app/apps/web
RUN pnpm run build
CMD [ "pnpm","run","start"]