on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: docker setup
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: test
        run: |
          echo "your message here"
          docker build -f ./docker/Dockerfile.backend -t turbo-be .
          docker build -f ./docker/Dockerfile.ws -t turbo-ws .
          docker build -f ./docker/Dockerfile.web -t turbo-web .
          
          docker push mukulpretham/turbo-be
          docker push mukulpretham/turbo-ws
          docker push mukulpretham/turbo-web