on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: docker setup
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: build and push to docker image
        run: |
          echo "your message here"
          docker build -f ./docker/Dockerfile.backend -t turbo-be .
          docker build -f ./docker/Dockerfile.ws -t turbo-ws .
          docker build -f ./docker/Dockerfile.web -t turbo-web .

          docker tag turbo-be mukulpretham/turbo-be:latest
          docker tag turbo-ws mukulpretham/turbo-ws:latest
          docker tag turbo-web mukulpretham/turbo-web:latest

          docker push mukulpretham/turbo-be:latest
          docker push mukulpretham/turbo-ws:latest
          docker push mukulpretham/turbo-web:latest
      
      - name: Deploy to VM
        run : | 
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem 
          chmod 600 key.pem 
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@${{secrets.VM_IP}} << 'EOF'
            sudo echo "Hellods,d ssh was sucessfull"
            sudo docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
            sudo docker pull mukulpretham/turbo-web
            sudo docker pull mukulpretham/turbo-ws
            sudo docker pull mukulpretham/turbo-be
            sudo docker network create turbo
            sudo docker run -d --name my_postgres -e POSTGRES_PASSWORD=your_password -p 5432:5432 --network turbo postgres
            sudo docker run -d --name turbo-ws -e DATABASE_URL="postgres://postgres:your_password@my_postgres:5432/todo_app" -p 8080:8080 --network turbo mukulpretham/turbo-ws
            sudo docker run -d --name turbo-web -e DATABASE_URL="postgres://postgres:your_password@my_postgres:5432/todo_app" -p 3000:3000 --network turbo mukulpretham/turbo-web
            sudo docker run -d --name turbo-be -e DATABASE_URL="postgres://postgres:your_password@my_postgres:5432/todo_app" -p 3001:3001 --network turbo mukulpretham/turbo-be
            
          EOF


